"""Add data tables.

Revision ID: 3544d0bf6815
Revises: 
Create Date: 2024-01-25 21:06:50.858058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3544d0bf6815'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(length=3), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('tid', name=op.f('pk_team'))
    )
    op.create_table('game',
    sa.Column('gid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('atid', sa.Integer(), nullable=False),
    sa.Column('atg', sa.Integer(), nullable=False),
    sa.Column('htid', sa.Integer(), nullable=False),
    sa.Column('htg', sa.Integer(), nullable=False),
    sa.Column('end', sa.String(length=2), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.ForeignKeyConstraint(['atid'], ['team.tid'], name=op.f('fk_game_atid_team')),
    sa.ForeignKeyConstraint(['htid'], ['team.tid'], name=op.f('fk_game_htid_team')),
    sa.PrimaryKeyConstraint('gid', name=op.f('pk_game'))
    )
    op.create_table('player',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pos', sa.String(length=2), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_player_tid_team')),
    sa.PrimaryKeyConstraint('pid', name=op.f('pk_player'))
    )
    op.create_table('game_player_join',
    sa.Column('game_gid', sa.Integer(), nullable=False),
    sa.Column('player_pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_gid'], ['game.gid'], name=op.f('fk_game_player_join_game_gid_game')),
    sa.ForeignKeyConstraint(['player_pid'], ['player.pid'], name=op.f('fk_game_player_join_player_pid_player')),
    sa.PrimaryKeyConstraint('game_gid', 'player_pid', name=op.f('pk_game_player_join'))
    )
    op.create_table('game_team_join',
    sa.Column('game_gid', sa.Integer(), nullable=False),
    sa.Column('team_tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_gid'], ['game.gid'], name=op.f('fk_game_team_join_game_gid_game')),
    sa.ForeignKeyConstraint(['team_tid'], ['team.tid'], name=op.f('fk_game_team_join_team_tid_team')),
    sa.PrimaryKeyConstraint('game_gid', 'team_tid', name=op.f('pk_game_team_join'))
    )
    op.create_table('goalie',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('dec', sa.String(), nullable=False),
    sa.Column('ga', sa.Integer(), nullable=False),
    sa.Column('sa', sa.Integer(), nullable=False),
    sa.Column('sv', sa.Integer(), nullable=False),
    sa.Column('svp', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('en', sa.Boolean(), nullable=False),
    sa.Column('enga', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMPS(0)'), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['game.gid'], name=op.f('fk_goalie_gid_game')),
    sa.ForeignKeyConstraint(['pid'], ['player.pid'], name=op.f('fk_goalie_pid_player')),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_goalie_tid_team')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_goalie'))
    )
    op.create_table('player_stat',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('g', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('pm', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('evg', sa.Integer(), nullable=False),
    sa.Column('ppg', sa.Integer(), nullable=False),
    sa.Column('shg', sa.Integer(), nullable=False),
    sa.Column('gwg', sa.Integer(), nullable=False),
    sa.Column('esa', sa.Integer(), nullable=False),
    sa.Column('ppa', sa.Integer(), nullable=False),
    sa.Column('sha', sa.Integer(), nullable=False),
    sa.Column('sog', sa.Integer(), nullable=False),
    sa.Column('sp', sa.Float(), nullable=False),
    sa.Column('shft', sa.Integer(), nullable=False),
    sa.Column('toi', sa.Interval(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMPS(0)'), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['game.gid'], name=op.f('fk_player_stat_gid_game')),
    sa.ForeignKeyConstraint(['pid'], ['player.pid'], name=op.f('fk_player_stat_pid_player')),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_player_stat_tid_team')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_player_stat'))
    )
    op.create_table('player_stat_advanced',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('icf', sa.Integer(), nullable=False),
    sa.Column('satf', sa.Integer(), nullable=False),
    sa.Column('sata', sa.Integer(), nullable=False),
    sa.Column('cfp', sa.Float(), nullable=False),
    sa.Column('crel', sa.Float(), nullable=False),
    sa.Column('zso', sa.Integer(), nullable=False),
    sa.Column('dzs', sa.Integer(), nullable=False),
    sa.Column('ozsp', sa.Float(), nullable=False),
    sa.Column('hit', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMPS(0)'), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['game.gid'], name=op.f('fk_player_stat_advanced_gid_game')),
    sa.ForeignKeyConstraint(['pid'], ['player.pid'], name=op.f('fk_player_stat_advanced_pid_player')),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_player_stat_advanced_tid_team')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_player_stat_advanced'))
    )
    op.create_table('team_stat',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('g', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('evg', sa.Integer(), nullable=False),
    sa.Column('ppg', sa.Integer(), nullable=False),
    sa.Column('shg', sa.Integer(), nullable=False),
    sa.Column('sog', sa.Integer(), nullable=False),
    sa.Column('sp', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMPS(0)'), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['game.gid'], name=op.f('fk_team_stat_gid_game')),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_team_stat_tid_team')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_team_stat'))
    )
    op.create_table('team_stat_advanced',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('satf', sa.Integer(), nullable=False),
    sa.Column('sata', sa.Integer(), nullable=False),
    sa.Column('cfp', sa.Float(), nullable=False),
    sa.Column('ozsp', sa.Float(), nullable=False),
    sa.Column('hit', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), onupdate=sa.text('CURRENT_TIMESTAMPS(0)'), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['game.gid'], name=op.f('fk_team_stat_advanced_gid_game')),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_team_stat_advanced_tid_team')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_team_stat_advanced'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_stat_advanced')
    op.drop_table('team_stat')
    op.drop_table('player_stat_advanced')
    op.drop_table('player_stat')
    op.drop_table('goalie')
    op.drop_table('game_team_join')
    op.drop_table('game_player_join')
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('team')
    # ### end Alembic commands ###
