"""Change nullable parameter.

Revision ID: 4440add3a361
Revises: 3544d0bf6815
Create Date: 2024-01-26 15:10:53.350657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4440add3a361'
down_revision: Union[str, None] = '3544d0bf6815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_game_player_join_game_gid'), 'game_player_join', ['game_gid'], unique=False)
    op.create_index(op.f('ix_game_player_join_player_pid'), 'game_player_join', ['player_pid'], unique=False)
    op.create_index(op.f('ix_game_team_join_game_gid'), 'game_team_join', ['game_gid'], unique=False)
    op.create_index(op.f('ix_game_team_join_team_tid'), 'game_team_join', ['team_tid'], unique=False)
    op.alter_column('goalie', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('player', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('player_stat', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('player_stat_advanced', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_stat', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_stat_advanced', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_stat_advanced', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('team_stat', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('team', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('player_stat_advanced', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('player_stat', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('player', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('goalie', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_game_team_join_team_tid'), table_name='game_team_join')
    op.drop_index(op.f('ix_game_team_join_game_gid'), table_name='game_team_join')
    op.drop_index(op.f('ix_game_player_join_player_pid'), table_name='game_player_join')
    op.drop_index(op.f('ix_game_player_join_game_gid'), table_name='game_player_join')
    op.alter_column('game', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
