"""Recreating GoalieStat object for adding toi column and preserving column postions.

Revision ID: 4ae7abf3c548
Revises: 6a6f33569f21
Create Date: 2024-02-24 11:23:33.757467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae7abf3c548'
down_revision: Union[str, None] = '6a6f33569f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie_stat',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('dec', sa.String(), nullable=False),
    sa.Column('ga', sa.Integer(), nullable=False),
    sa.Column('sa', sa.Integer(), nullable=False),
    sa.Column('sv', sa.Integer(), nullable=False),
    sa.Column('svp', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('toi', sa.Interval(), nullable=False),
    sa.Column('en', sa.Boolean(), nullable=False),
    sa.Column('enga', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['game.gid'], name=op.f('fk_goalie_stat_gid_game')),
    sa.ForeignKeyConstraint(['pid'], ['player.pid'], name=op.f('fk_goalie_stat_pid_player')),
    sa.ForeignKeyConstraint(['tid'], ['team.tid'], name=op.f('fk_goalie_stat_tid_team')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_goalie_stat'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goalie_stat')
    # ### end Alembic commands ###
