"""Adding toi column into GameStat object.

Revision ID: 6a6f33569f21
Revises: b5240ca94483
Create Date: 2024-02-24 11:01:42.886730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6f33569f21'
down_revision: Union[str, None] = 'b5240ca94483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goalie_stat', sa.Column('toi', sa.Interval(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goalie_stat', 'toi')
    # ### end Alembic commands ###
