"""Remove number column in Player object.

Revision ID: f1416f18d188
Revises: 4440add3a361
Create Date: 2024-02-17 23:54:56.569907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1416f18d188'
down_revision: Union[str, None] = '4440add3a361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
